# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src/crypto"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/agents"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/chaos"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/src/controllers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
