// src/controllers/api/v1/zz_generated.deepcopy.go
//go:build !ignore_autogenerated

package v1

import (
    "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Qraiop) DeepCopyInto(out *Qraiop) {
    *out = *in
    out.TypeMeta = in.TypeMeta
    in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
    out.Spec = in.Spec
    out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Qraiop.
func (in *Qraiop) DeepCopy() *Qraiop {
    if in == nil {
        return nil
    }
    out := new(Qraiop)
    in.DeepCopyInto(out)
    return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Qraiop) DeepCopyObject() runtime.Object {
    if c := in.DeepCopy(); c != nil {
        return c
    }
    return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QraiopList) DeepCopyInto(out *QraiopList) {
    *out = *in
    out.TypeMeta = in.TypeMeta
    in.ListMeta.DeepCopyInto(&out.ListMeta)
    if in.Items != nil {
        in, out := &in.Items, &out.Items
        *out = make([]Qraiop, len(*in))
        for i := range *in {
            (*in)[i].DeepCopyInto(&(*out)[i])
        }
    }
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QraiopList.
func (in *QraiopList) DeepCopy() *QraiopList {
    if in == nil {
        return nil
    }
    out := new(QraiopList)
    in.DeepCopyInto(out)
    return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QraiopList) DeepCopyObject() runtime.Object {
    if c := in.DeepCopy(); c != nil {
        return c
    }
    return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QraiopSpec) DeepCopyInto(out *QraiopSpec) {
    *out = *in
    out.Cryptography = in.Cryptography
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QraiopSpec.
func (in *QraiopSpec) DeepCopy() *QraiopSpec {
    if in == nil {
        return nil
    }
    out := new(QraiopSpec)
    in.DeepCopyInto(out)
    return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QraiopStatus) DeepCopyInto(out *QraiopStatus) {
    *out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QraiopStatus.
func (in *QraiopStatus) DeepCopy() *QraiopStatus {
    if in == nil {
        return nil
    }
    out := new(QraiopStatus)
    in.DeepCopyInto(out)
    return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CryptographyConfig) DeepCopyInto(out *CryptographyConfig) {
    *out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CryptographyConfig.
func (in *CryptographyConfig) DeepCopy() *CryptographyConfig {
    if in == nil {
        return nil
    }
    out := new(CryptographyConfig)
    in.DeepCopyInto(out)
    return out
}
