[package]
name = "qraiop-crypto"
version = "0.1.0"
edition = "2021"
authors = ["Bailey Richardson <bailey@qraiop.io>"]
description = "Quantum-resilient cryptography library for QRAIOP"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["quantum-safe"]
quantum-safe = []

[[bin]]
name = "qraiop-crypto-demo"
path = "src/main.rs"
